#include "lang.h"

typedef struct {
    const char* en;
    const char* zh;
} LangEntry;

#define LANG_E(key, en_str, zh_str) [key] = {en_str, zh_str}

static const LangEntry lang_entries[LANG_COUNT] = {
    LANG_E(LANG_ABOUT, "About", "关于"),
    LANG_E(LANG_ACHIEVEMENT_SORT_ORDER, "Achievement Sort Order", "成就排序方式"),
    LANG_E(LANG_ACHIEVEMENT_TRACKING_SETTINGS, "Achievement tracking settings", "成就追踪设置"),
    LANG_E(LANG_APPEARANCE, "Appearance", "外观"),
    LANG_E(LANG_ASSIGNMENTS, "Assignments", "按键分配"),
    LANG_E(LANG_AUTHENTICATE, "Authenticate", "验证"),
    LANG_E(LANG_AUTHENTICATION_STATUS, "Authentication status", "验证状态"),
    LANG_E(LANG_BLUE_GAIN, "Blue gain", "蓝色增益"),
    LANG_E(LANG_BLUETOOTH, "Bluetooth", "蓝牙"),
    LANG_E(LANG_BOLD, "Bold", "粗体"),
    LANG_E(LANG_BOTH, "Both", "两者"),
    LANG_E(LANG_BRIGHTNESS, "Brightness", "亮度"),
    LANG_E(LANG_BRIGHTNESS_WHEN_TOGGLED, "Brightness when toggled", "切换时亮度"),
    LANG_E(LANG_BUSYBOX_VERSION, "Busybox version", "Busybox 版本"),
    LANG_E(LANG_COLOR_TEMPERATURE, "Color temperature", "色温"),
    LANG_E(LANG_COLOR_TEMPERATURE_0_TO_40, "Color temperature (0 to 40)", "色温(0-40)"),
    LANG_E(LANG_COLOR_TEMPERATURE_WHEN_TOGGLED, "Color temperature when toggled", "切换时色温"),
    LANG_E(LANG_CONTRAST, "Contrast", "对比度"),
    LANG_E(LANG_CONTRAST_ENHANCEMENT_4_TO_5, "Contrast enhancement (-4 to 5)", "对比度增强(-4 到 5)"),
    LANG_E(LANG_CONTRAST_WHEN_TOGGLED, "Contrast when toggled", "切换时对比度"),
    LANG_E(LANG_CUSTOMIZE_BUTTON_ASSIGNMENTS, "Customize button assignments", "自定义按键分配"),
    LANG_E(LANG_DEFAULT_VIEW, "Default view", "默认视图"),
    LANG_E(LANG_DISABLE_SAVE_STATES_AND_CHEATS_FOR_ACHIEVEMENTS, "Disable save states and cheats for achievements", "禁用成就所需的存档与作弊"),
    LANG_E(LANG_DISPLAY, "Display", "显示"),
    LANG_E(LANG_DISPLAY_BRIGHTNESS_0_TO_10, "Display brightness (0 to 10)", "显示亮度(0-10)"),
    LANG_E(LANG_DOWN, "Down", "下"),
    LANG_E(LANG_DPAD, "Dpad", "十字键"),
    LANG_E(LANG_DPAD_MODE_WHEN_TOGGLED, "Dpad mode when toggled", "切换时十字键模式"),
    LANG_E(LANG_DURATION, "Duration", "持续时长"),
    LANG_E(LANG_DURATION_FOR_PROGRESS_UPDATES_TOP_LEFT_OFF_TO_DISABLE, "Duration for progress updates (top-left). Off to disable.", "进度更新(左上角)持续时长。关闭以禁用。"),
    LANG_E(LANG_EMPTY_FOLDER, "Empty folder", "空文件夹"),
    LANG_E(LANG_ENABLE_ACHIEVEMENTS, "Enable Achievements", "启用成就"),
    LANG_E(LANG_ENABLE_RETROACHIEVEMENTS_INTEGRATION, "Enable RetroAchievements integration", "启用成就系统集成"),
    LANG_E(LANG_ENABLE_OR_DISABLE_HAPTIC_FEEDBACK_ON_CERTAIN_ACTIONS_IN_THE_OS, "Enable or disable haptic feedback on certain actions in the OS", "开启或关闭系统操作的震动反馈"),
    LANG_E(LANG_ENABLE_OR_DISABLE_MENU_ANIMATIONS, "Enable or disable menu animations", "开启或关闭菜单动画"),
    LANG_E(LANG_ENABLE_TURBO_FIRE_A, "Enable turbo fire A", "启用连发 A"),
    LANG_E(LANG_ENABLE_TURBO_FIRE_B, "Enable turbo fire B", "启用连发 B"),
    LANG_E(LANG_ENABLE_TURBO_FIRE_L1, "Enable turbo fire L1", "启用连发 L1"),
    LANG_E(LANG_ENABLE_TURBO_FIRE_L2, "Enable turbo fire L2", "启用连发 L2"),
    LANG_E(LANG_ENABLE_TURBO_FIRE_R1, "Enable turbo fire R1", "启用连发 R1"),
    LANG_E(LANG_ENABLE_TURBO_FIRE_R2, "Enable turbo fire R2", "启用连发 R2"),
    LANG_E(LANG_ENABLE_TURBO_FIRE_X, "Enable turbo fire X", "启用连发 X"),
    LANG_E(LANG_ENABLE_TURBO_FIRE_Y, "Enable turbo fire Y", "启用连发 Y"),
    LANG_E(LANG_EXPOSURE, "Exposure", "曝光"),
    LANG_E(LANG_EXPOSURE_ENHANCEMENT_4_TO_5, "Exposure enhancement (-4 to 5)", "曝光增强(-4 到 5)"),
    LANG_E(LANG_EXPOSURE_WHEN_TOGGLED, "Exposure when toggled", "切换时曝光"),
    LANG_E(LANG_FN_SWITCH, "FN switch", "FN 开关"),
    LANG_E(LANG_FN_SWITCH_DISABLES_LED, "FN switch disables LED", "FN 开关关闭 LED"),
    LANG_E(LANG_FN_SWITCH_SETTINGS, "FN switch settings", "FN 开关设置"),
    LANG_E(LANG_FAN_SPEED, "Fan Speed", "风扇速度"),
    LANG_E(LANG_FONT, "Font", "字体"),
    LANG_E(LANG_FONT_STYLE, "Font style", "字型"),
    LANG_E(LANG_GAME_ART_CORNER_RADIUS, "Game art corner radius", "封面圆角"),
    LANG_E(LANG_GAME_ART_WIDTH, "Game art width", "封面宽度"),
    LANG_E(LANG_GAME_SWITCHER_CURTAIN_OPACITY, "Game switcher curtain opacity", "游戏切换器遮罩透明度"),
    LANG_E(LANG_GAME_SWITCHER_SCALING, "Game switcher scaling", "游戏切换器缩放"),
    LANG_E(LANG_GREEN_GAIN, "Green gain", "绿色增益"),
    LANG_E(LANG_HAPTIC_FEEDBACK, "Haptic feedback", "震动反馈"),
    LANG_E(LANG_HARDCORE_MODE, "Hardcore Mode", "硬核模式"),
    LANG_E(LANG_HOME, "Home", "主页"),
    LANG_E(LANG_HOW_ACHIEVEMENTS_ARE_SORTED_IN_THE_IN_GAME_MENU, "How achievements are sorted in the in-game menu", "成就排序方式"),
    LANG_E(LANG_HOW_LONG_ACHIEVEMENT_NOTIFICATIONS_STAY_ON_SCREEN, "How long achievement notifications stay on screen", "成就通知在屏幕上的显示时长"),
    LANG_E(LANG_HOW_LONG_NOTIFICATIONS_STAY_ON_SCREEN, "How long notifications stay on screen", "通知在屏幕上的显示时长"),
    LANG_E(LANG_IF_ENABLED__USED_THE_EMULATOR_BACKGROUND_IMAGE_OTHERWISE_USES_THE_DEFAULT, "If enabled, used the emulator background image. Otherwise uses the default.", "启用后使用模拟器背景图片,否则使用默认背景。"),
    LANG_E(LANG_IN_GAME, "In-Game", "游戏中"),
    LANG_E(LANG_IN_GAME_SETTINGS_FOR_MINARCH, "In-game settings for MinArch", "MinArch 游戏内设置"),
    LANG_E(LANG_INPUT_PROMPT_STYLE, "Input prompt style", "按键提示风格"),
    LANG_E(LANG_JOYSTICK, "Joystick", "摇杆"),
    LANG_E(LANG_KEEP_AWAKE_OVER_USB, "Keep awake over USB", "USB 连接时保持唤醒"),
    LANG_E(LANG_L_R, "L/R", "L/R"),
    LANG_E(LANG_LEFT, "Left", "左"),
    LANG_E(LANG_LOAD_STATES, "Load states", "读取存档"),
    LANG_E(LANG_MENU_TRANSITIONS, "Menu transitions", "菜单过渡"),
    LANG_E(LANG_NETWORK, "Network", "网络"),
    LANG_E(LANG_NEXTUI_VERSION, "NextUI version", "NextUI 版本"),
    LANG_E(LANG_NO_PREVIEW, "No Preview", "无预览"),
    LANG_E(LANG_NO_RECENTS, "No Recents", "暂无最近游玩"),
    LANG_E(LANG_NORMAL, "Normal", "常规"),
    LANG_E(LANG_NOTIFICATION_DURATION, "Notification Duration", "通知持续时长"),
    LANG_E(LANG_NOTIFICATIONS, "Notifications", "通知"),
    LANG_E(LANG_PASSWORD, "Password", "密码"),
    LANG_E(LANG_PERIOD_OF_INACTIVITY_BEFORE_SCREEN_TURNS_OFF_0_600S, "Period of inactivity before screen turns off (0-600s)", "屏幕关闭前无操作等待时间(0-600 秒)"),
    LANG_E(LANG_PLATFORM, "Platform", "平台"),
    LANG_E(LANG_POWER, "Power", "电源"),
    LANG_E(LANG_POWEROFF, "Poweroff", "关机"),
    LANG_E(LANG_PROGRESS_DURATION, "Progress Duration", "进度更新持续时长"),
    LANG_E(LANG_REBOOT, "Reboot", "重启"),
    LANG_E(LANG_RED_GAIN, "Red gain", "红色增益"),
    LANG_E(LANG_RESET_TO_DEFAULTS, "Reset to defaults", "恢复默认设置"),
    LANG_E(LANG_RESETS_ALL_OPTIONS_IN_THIS_MENU_TO_THEIR_DEFAULT_VALUES, "Resets all options in this menu to their default values.", "将此菜单中所有选项重置为默认值。"),
    LANG_E(LANG_RETROACHIEVEMENTS, "RetroAchievements", "成就系统"),
    LANG_E(LANG_RETROACHIEVEMENTS_PASSWORD, "RetroAchievements password", "RetroAchievements 密码"),
    LANG_E(LANG_RETROACHIEVEMENTS_USERNAME, "RetroAchievements username", "RetroAchievements 用户名"),
    LANG_E(LANG_RIGHT, "Right", "右"),
    LANG_E(LANG_SAFE_POWEROFF, "Safe poweroff", "安全关机"),
    LANG_E(LANG_SATURATION, "Saturation", "饱和度"),
    LANG_E(LANG_SATURATION_ENHANCEMENT_5_TO_5, "Saturation enhancement (-5 to 5)", "饱和度增强(-5 到 5)"),
    LANG_E(LANG_SATURATION_WHEN_TOGGLED, "Saturation when toggled", "切换时饱和度"),
    LANG_E(LANG_SAVE_FORMAT, "Save format", "存档格式"),
    LANG_E(LANG_SAVE_STATE_FORMAT, "Save state format", "即时存档格式"),
    LANG_E(LANG_SAVE_STATE_NOTIFICATIONS, "Save state notifications", "即时存档通知"),
    LANG_E(LANG_SAVE_STATES, "Save states", "即时存档"),
    LANG_E(LANG_SCREEN_TIMEOUT, "Screen timeout", "屏幕超时"),
    LANG_E(LANG_SCREENSHOTS, "Screenshots", "截图"),
    LANG_E(LANG_SELECT_THE_STYLE_OF_INPUT_PROMPTS, "Select the style of input prompts.", "选择按键提示样式。"),
    LANG_E(LANG_SET_THE_RADIUS_FOR_THE_ROUNDED_CORNERS_OF_GAME_ART, "Set the radius for the rounded corners of game art", "设置游戏封面圆角半径"),
    LANG_E(LANG_SET_TIME_AND_DATE_AUTOMATICALLY, "Set time and date automatically", "自动设置时间与日期"),
    LANG_E(LANG_SHOW_24H_TIME_FORMAT, "Show 24h time format", "24 小时制时间格式"),
    LANG_E(LANG_SHOW_NOTIFICATIONS, "Show Notifications", "显示通知"),
    LANG_E(LANG_SHOW_QUICKSWITCHER_UI, "Show Quickswitcher UI", "显示快速切换界面"),
    LANG_E(LANG_SHOW_RECENTS, "Show Recents", "显示最近游玩"),
    LANG_E(LANG_SHOW_TOOLS, "Show Tools", "显示工具"),
    LANG_E(LANG_SHOW_ACHIEVEMENT_UNLOCK_NOTIFICATIONS, "Show achievement unlock notifications", "显示成就解锁通知"),
    LANG_E(LANG_SHOW_BATTERY_LEVEL_AS_PERCENT_IN_THE_STATUS_PILL, "Show battery level as percent in the status pill", "在状态栏中以百分比显示电量"),
    LANG_E(LANG_SHOW_BATTERY_PERCENTAGE, "Show battery percentage", "显示电量百分比"),
    LANG_E(LANG_SHOW_CLOCK, "Show clock", "显示时钟"),
    LANG_E(LANG_SHOW_CLOCK_IN_THE_24HRS_TIME_FORMAT, "Show clock in the 24hrs time format", "24 小时制显示时钟"),
    LANG_E(LANG_SHOW_CLOCK_IN_THE_STATUS_PILL, "Show clock in the status pill", "状态栏显示时钟"),
    LANG_E(LANG_SHOW_FOLDER_NAMES_AT_ROOT, "Show folder names at root", "根目录显示文件夹名"),
    LANG_E(LANG_SHOW_FOLDER_NAMES_AT_ROOT_DIRECTORY, "Show folder names at root directory", "根目录显示文件夹名称"),
    LANG_E(LANG_SHOW_GAME_ART, "Show game art", "显示游戏封面"),
    LANG_E(LANG_SHOW_GAME_ARTWORK_IN_THE_MAIN_MENU, "Show game artwork in the main menu", "主菜单显示游戏封面"),
    LANG_E(LANG_SHOW_MENU_ANIMATIONS, "Show menu animations", "显示菜单动画"),
    LANG_E(LANG_SHOW_NOTIFICATION_WHEN_LOADING_GAME_STATE, "Show notification when loading game state", "读取游戏状态时显示通知"),
    LANG_E(LANG_SHOW_NOTIFICATION_WHEN_SAVING_GAME_STATE, "Show notification when saving game state", "保存游戏状态时显示通知"),
    LANG_E(LANG_SHOW_NOTIFICATION_WHEN_TAKING_A_SCREENSHOT, "Show notification when taking a screenshot", "截图时显示通知"),
    LANG_E(LANG_SLEEP, "Sleep", "休眠"),
    LANG_E(LANG_SPEAKER_VOLUME, "Speaker volume", "扬声器音量"),
    LANG_E(LANG_SPEAKER_VOLUME_0_20, "Speaker volume (0-20)", "扬声器音量(0-20)"),
    LANG_E(LANG_STATUS, "Status", "状态"),
    LANG_E(LANG_STOCK_OS_VERSION, "Stock OS version", "原厂系统版本"),
    LANG_E(LANG_STYLE_OF_ANIMATED_TRANSITION_WHEN_NAVIGATING_MENUS, "Style of animated transition when navigating menus", "菜单导航时的动画过渡风格"),
    LANG_E(LANG_SUSPEND_TIMEOUT, "Suspend timeout", "待机超时"),
    LANG_E(LANG_SWITCH_WILL_ALSO_DISABLE_LEDS, "Switch will also disable LEDs", "开关也会关闭 LED"),
    LANG_E(LANG_SYNC_OFFLINE_UNLOCKS, "Sync Offline Unlocks", "同步离线解锁"),
    LANG_E(LANG_SYSTEM, "System", "系统"),
    LANG_E(LANG_TEST_CREDENTIALS_AND_RETRIEVE_API_TOKEN, "Test credentials and retrieve API token", "测试凭据并获取 API 令牌"),
    LANG_E(LANG_THE_FONT_TO_RENDER_ALL_UI_TEXT, "The font to render all UI text.", "用于渲染所有 UI 文本的字体。"),
    LANG_E(LANG_THE_INITIAL_VIEW_TO_SHOW_ON_BOOT, "The initial view to show on boot", "开机时显示的初始视图"),
    LANG_E(LANG_THE_SCALING_ALGORITHM_USED_TO_DISPLAY_THE_SAVEGAME_IMAGE, "The scaling algorithm used to display the savegame image.", "用于显示存档截图的缩放算法。"),
    LANG_E(LANG_THE_STYLE_TO_RENDER_THE_UI_FONT_E_G_BOLD, "The style to render the UI font (e.g. bold)", "UI 字体的渲染样式(如粗体)"),
    LANG_E(LANG_TIME_BEFORE_DEVICE_GOES_TO_SLEEP_AFTER_SCREEN_IS_OFF_5_600S, "Time before device goes to sleep after screen is off (5-600s)", "屏幕关闭后进入待机的等待时间(5-600 秒)"),
    LANG_E(LANG_TIME_ZONE, "Time zone", "时区"),
    LANG_E(LANG_TURBO_FIRE_A, "Turbo fire A", "连发 A"),
    LANG_E(LANG_TURBO_FIRE_B, "Turbo fire B", "连发 B"),
    LANG_E(LANG_TURBO_FIRE_L1, "Turbo fire L1", "连发 L1"),
    LANG_E(LANG_TURBO_FIRE_L2, "Turbo fire L2", "连发 L2"),
    LANG_E(LANG_TURBO_FIRE_R1, "Turbo fire R1", "连发 R1"),
    LANG_E(LANG_TURBO_FIRE_R2, "Turbo fire R2", "连发 R2"),
    LANG_E(LANG_TURBO_FIRE_X, "Turbo fire X", "连发 X"),
    LANG_E(LANG_TURBO_FIRE_Y, "Turbo fire Y", "连发 Y"),
    LANG_E(LANG_U_D, "U/D", "U/D"),
    LANG_E(LANG_UI_CUSTOMIZATION, "UI customization", "界面定制"),
    LANG_E(LANG_UP, "Up", "上"),
    LANG_E(LANG_USE_EXTRACTED_FILE_NAME, "Use extracted file name", "使用解压后的文件名"),
    LANG_E(LANG_USE_FOLDER_BACKGROUND_FOR_ROMS, "Use folder background for ROMs", "为 ROM 使用文件夹背景"),
    LANG_E(LANG_USERNAME, "Username", "用户名"),
    LANG_E(LANG_VOLUME, "Volume", "音量"),
    LANG_E(LANG_VOLUME_WHEN_TOGGLED, "Volume when toggled", "切换时音量"),
    LANG_E(LANG_WHITE_POINT_CORRECTION, "White point correction", "白点校正"),
    LANG_E(LANG_WHITE_POINT_CORRECTION_BLUE_CHANNEL_GAIN_0_TO_200, "White point correction blue channel gain (0 to 200)", "白点校正蓝色通道增益(0-200)"),
    LANG_E(LANG_WHITE_POINT_CORRECTION_GREEN_CHANNEL_GAIN_0_TO_200, "White point correction green channel gain (0 to 200)", "白点校正绿色通道增益(0-200)"),
    LANG_E(LANG_WHITE_POINT_CORRECTION_RED_CHANNEL_GAIN_0_TO_200, "White point correction red channel gain (0 to 200)", "白点校正红色通道增益(0-200)"),
    LANG_E(LANG_WIFI, "Wifi", "WiFi"),
    LANG_E(LANG_YOUR_TIME_ZONE, "Your time zone", "时区设置"),
    LANG_E(LANG_LANGUAGE, "Language", "语言"),
    LANG_E(LANG_LANGUAGE_DESC, "Choose UI language", "选择界面语言"),
    LANG_E(LANG_ENGLISH, "English", "English"),
    LANG_E(LANG_SIMPLIFIED_CHINESE, "简体中文", "简体中文"),
    LANG_E(LANG_CONTINUE, "Continue", "继续"),
    LANG_E(LANG_RESET, "Reset", "重置"),
    LANG_E(LANG_FRONTEND, "Frontend", "前端"),
    LANG_E(LANG_EMULATOR, "Emulator", "模拟器"),
    LANG_E(LANG_SHADERS, "Shaders", "着色器"),
    LANG_E(LANG_CHEATS, "Cheats", "作弊码"),
    LANG_E(LANG_CONTROLS, "Controls", "按键设置"),
    LANG_E(LANG_SHORTCUTS, "Shortcuts", "快捷键"),
    LANG_E(LANG_ACHIEVEMENTS, "Achievements", "成就"),
    LANG_E(LANG_SAVE_CHANGES, "Save Changes", "保存更改"),
    LANG_E(LANG_BACK, "BACK", "返回"),
    LANG_E(LANG_MUTE, "MUTE", "静音"),
    LANG_E(LANG_UNMUTE, "UNMUTE", "取消静音"),
    LANG_E(LANG_OKAY, "OKAY", "确定"),
    LANG_E(LANG_MENU_BTN, "MENU", "菜单"),
    LANG_E(LANG_SLEEP_BTN, "SLEEP", "休眠"),
    LANG_E(LANG_SHOW_ALL, "SHOW ALL", "显示全部"),
    LANG_E(LANG_SHOW_LOCKED, "SHOW LOCKED", "显示锁定"),
    LANG_E(LANG_NO_ACHIEVEMENTS_FOUND, "No achievements found", "未找到成就"),
    LANG_E(LANG_FAILED_TO_LOAD_ACHIEVEMENTS, "Failed to load achievements", "加载成就失败"),
    LANG_E(LANG_ACHIEVEMENT_LIST_NOT_AVAILABLE, "Achievement list not available", "成就列表不可用"),
    LANG_E(LANG_UNKNOWN_EMULATOR, "Unknown Emulator", "未知模拟器"),
    LANG_E(LANG_UNSUPPORTED_GAME_VERSION, "Unsupported Game Version", "不支持的游戏版本"),
    LANG_E(LANG_SCREENSHOT_SAVED, "Screenshot saved", "截图已保存"),
    LANG_E(LANG_EMPTY_SLOT, "Empty Slot", "空存档位"),
    LANG_E(LANG_MUTED_PROGRESS_SILENCED, "Muted - progress notifications silenced", "已静音 — 进度通知已关闭"),
    LANG_E(LANG_UNLOCKED_OFFLINE_PENDING_SYNC, "Unlocked offline - pending sync", "离线解锁 — 待同步"),
    LANG_E(LANG_STATE_SAVED_SLOT, "State Saved - Slot %d", "已保存存档 - 位 %d"),
    LANG_E(LANG_SAVE_FAILED_SLOT, "Save Failed - Slot %d", "保存失败 - 位 %d"),
    LANG_E(LANG_STATE_LOADED_SLOT, "State Loaded - Slot %d", "已读取存档 - 位 %d"),
    LANG_E(LANG_LOAD_FAILED_SLOT, "Load Failed - Slot %d", "读取失败 - 位 %d"),
    LANG_E(LANG_DISC_I, "Disc %i", "光盘 %i"),
    LANG_E(LANG_PROGRESS_COLON, "Progress: %s", "进度: %s"),
    LANG_E(LANG_THIS_CATEGORY_HAS_NO_OPTIONS, "This category has no options.", "此分类没有选项。"),
    LANG_E(LANG_THIS_CORE_HAS_NO_OPTIONS, "This core has no options.", "此核心没有选项。"),
    LANG_E(LANG_PRESS_A_TO_SET_AND_X_TO_CLEAR, "Press A to set and X to clear.", "按 A 设置,按 X 清除。"),
    LANG_E(LANG_CONTROLLER, "Controller", "手柄"),
    LANG_E(LANG_SELECT_THE_TYPE_OF_CONTROLLER, "Select the type of controller.", "选择手柄类型。"),
    LANG_E(LANG_USING_DEFAULTS, "Using defaults.", "使用默认设置。"),
    LANG_E(LANG_USING_CONSOLE_CONFIG, "Using console config.", "使用主机配置。"),
    LANG_E(LANG_USING_GAME_CONFIG, "Using game config.", "使用游戏配置。"),
    LANG_E(LANG_SAVED_FOR_CONSOLE, "Saved for console.", "已为主机保存。"),
    LANG_E(LANG_SAVED_FOR_GAME, "Saved for game.", "已为游戏保存。"),
    LANG_E(LANG_RESTORED_CONSOLE_DEFAULTS, "Restored console defaults.", "已恢复主机默认设置。"),
    LANG_E(LANG_RESTORED_DEFAULTS, "Restored defaults.", "已恢复默认设置。"),
    LANG_E(LANG_SAVE_FOR_CONSOLE, "Save for console", "为主机保存"),
    LANG_E(LANG_SAVE_FOR_GAME, "Save for game", "为游戏保存"),
    LANG_E(LANG_RESTORE_DEFAULTS, "Restore defaults", "恢复默认设置"),
    LANG_E(LANG_CHEATS_DISABLED_HARDCORE, "Cheats disabled in Hardcore mode", "硬核模式下禁用作弊码"),
    LANG_E(LANG_NO_EXTRA_SETTINGS_FOUND, "No extra settings found", "未找到额外设置"),
    LANG_E(LANG_LOAD_STATES_DISABLED_HARDCORE, "Load states disabled in Hardcore mode", "硬核模式下禁用读取存档"),
    LANG_E(LANG_SAVE_STATES_DISABLED_HARDCORE, "Save states disabled in Hardcore mode", "硬核模式下禁用保存存档"),
    LANG_E(LANG_NO_CHEAT_FILE_LOADED, "No cheat file loaded.", "未加载作弊码文件。"),
    LANG_E(LANG_DUALSHOCK_TOGGLE_COMBO, "DualShock Toggle Combo", "DualShock 切换组合键"),
    LANG_E(LANG_PIXEL_PERFECT, "Pixel Perfect", "像素完美"),
    LANG_E(LANG_SHARP, "Sharp", "锐利"),
    LANG_E(LANG_SMOOTH, "Smooth", "平滑"),
    LANG_E(LANG_CRT, "CRT", "CRT"),
    LANG_E(LANG_SCANLINES, "Scanlines", "扫描线"),
    LANG_E(LANG_LCD, "LCD", "LCD"),
    LANG_E(LANG_BILINEAR, "Bilinear", "双线性"),
    LANG_E(LANG_NEAREST, "Nearest", "最近邻"),
    LANG_E(LANG_LINEAR, "Linear", "线性"),
    LANG_E(LANG_RESAMPLING_QUALITY_HIGHER_TAKES_MORE_CPU, "Resampling quality higher takes more CPU", "重采样质量越高 CPU 占用越大"),
    LANG_E(LANG_MAKES_YOUR_LEDS_FOLLOW_ON_SCREEN_COLORS, "Makes your leds follow on screen colors", "使 LED 跟随屏幕颜色变化"),
    LANG_E(LANG_LINEAR_SMOOTHS_LINES, "LINEAR smooths lines, but works better when final image is at higher resolution", "LINEAR 平滑线条,但在最终图像分辨率较高或使用着色器升采样时效果更好"),
    LANG_E(LANG_LZ4_ACCELERATION_FOR_REWIND, "LZ4 acceleration used for rewind snapshots.\\nLower values compress more but use more CPU.", "LZ4 加速用于倒带回放快照。\\n数值越低压缩越大但 CPU 占用越高。"),
    LANG_E(LANG_NO_SHADERS_AVAILABLE, "No shaders available", "无可用着色器"),
    LANG_E(LANG_SHADERS_FOLDER_NOT_FOUND, "/Shaders folder or shader files not found", "/Shaders 文件夹或着色器文件未找到"),
    LANG_E(LANG_SAVE, "Save", "保存"),
    LANG_E(LANG_LOAD, "Load", "读取"),
    LANG_E(LANG_OPTIONS, "Options", "选项"),
    LANG_E(LANG_QUIT, "Quit", "退出"),
    LANG_E(LANG_CONNECTING_DOTDOTDOT, "Connecting...", "连接中..."),
    LANG_E(LANG_OFFLINE, "Offline", "离线"),
    LANG_E(LANG_GAME_MASTERED, "Game Mastered!", "已完美通关!"),
    LANG_E(LANG_CONNECTING_TO_RETROACHIEVEMENTS, "Connecting to RetroAchievements...", "正在连接 RetroAchievements..."),
    LANG_E(LANG_RETROACHIEVEMENTS_CONNECTION_FAILED, "RetroAchievements: Connection failed", "RetroAchievements: 连接失败"),
    LANG_E(LANG_RE_APPLIED_OFFLINE_UNLOCKS, "Re-applied %u offline unlock(s) after ", "已重新应用 %u 个离线解锁(在 "),
    LANG_E(LANG_RE_APPLIED_OFFLINE_UNLOCKS_AFTER, "Re-applied %u offline unlock(s) after %s", "已重新应用 %u 个离线解锁(在 %s 后)"),
    LANG_E(LANG_AMBIENT_MODE, "Ambient Mode", "环境模式"),
    LANG_E(LANG_AUDIO_RESAMPLING_QUALITY, "Audio Resampling Quality", "音频重采样质量"),
    LANG_E(LANG_CHOOSE_A_CUSTOM_OVERLAY_PNG_FROM_THE_OVERLAYS_FOLDER, "Choose a custom overlay png from the Overlays folder", "从 Overlays 文件夹选择自定义叠加层 PNG"),
    LANG_E(LANG_COMPRESS_REWIND_SNAPSHOTS_TO_SAVE_MEMORY_AT_THE_COST_OF_CPU, "Compress rewind snapshots to save memory at the cost of CPU.", "压缩倒带回放快照以节省内存,代价是 CPU 增加"),
    LANG_E(LANG_CORE_SYNC, "Core Sync", "核心同步"),
    LANG_E(LANG_CPU_SPEED, "CPU Speed", "CPU 速度"),
    LANG_E(LANG_DEBUG_HUD, "Debug HUD", "调试 HUD"),
    LANG_E(LANG_FAST_FORWARD_AUDIO, "Fast forward audio", "快进时音频"),
    LANG_E(LANG_IF_SHADERS_HAVE_EXTRA_SETTINGS_THEY_WILL_SHOW_UP_IN_THIS_SETTINGS_MENU, "If shaders have extra settings they will show up in this settings menu", "若着色器有额外设置,会显示在此设置菜单中"),
    LANG_E(LANG_LINEAR_SMOOTHS_LINES_BUT_WORKS_BETTER_WHEN_FINAL_IMAGE_IS_AT_HIGHER_RESOLUTION_SO_EITHER_CORE_THAT_OUTPUTS_HIGHER_RESOLUTION_OR_UPSCALING_WITH_SHADERS, "LINEAR smooths lines, but works better when final image is at higher resolution, so either core that outputs higher resolution or upscaling with shaders", "LINEAR 平滑线条,但在最终图像分辨率较高或使用着色器升采样时效果更好"),
    LANG_E(LANG_MAX_FF_SPEED, "Max FF Speed", "最大快进速度"),
    LANG_E(LANG_METHOD_OF_UPSCALING_NEAREST_OR_LINEAR, "Method of upscaling, NEAREST or LINEAR", "升采样方法:最近邻或线性"),
    LANG_E(LANG_NUMBER_OF_SHADERS, "Number of Shaders", "着色器数量"),
    LANG_E(LANG_NUMBER_OF_SHADERS_1_TO_3, "Number of shaders 1 to 3", "着色器数量(1 到 3)"),
    LANG_E(LANG_OFFSET_SCREEN_X, "Offset screen X", "屏幕 X 偏移"),
    LANG_E(LANG_OFFSET_SCREEN_Y, "Offset screen Y", "屏幕 Y 偏移"),
    LANG_E(LANG_OFFSET_X_PIXELS, "Offset X pixels", "X 像素偏移"),
    LANG_E(LANG_OFFSET_Y_PIXELS, "Offset Y pixels", "Y 像素偏移"),
    LANG_E(LANG_OPTIONAL_SHADERS_SETTINGS, "Optional Shaders Settings", "着色器可选设置"),
    LANG_E(LANG_OVERLAY, "Overlay", "叠加层"),
    LANG_E(LANG_PLAY_OR_MUTE_AUDIO_WHEN_FAST_FORWARDING, "Play or mute audio when fast forwarding.", "快进时播放或静音音频"),
    LANG_E(LANG_PLAY_OR_MUTE_AUDIO_WHEN_REWINDING, "Play or mute audio when rewinding.", "倒带时播放或静音音频"),
    LANG_E(LANG_REWIND, "Rewind", "倒带"),
    LANG_E(LANG_REWIND_AUDIO, "Rewind audio", "倒带时音频"),
    LANG_E(LANG_REWIND_BUFFER_MB, "Rewind Buffer (MB)", "倒带缓存(MB)"),
    LANG_E(LANG_REWIND_COMPRESSION, "Rewind Compression", "倒带压缩"),
    LANG_E(LANG_REWIND_COMPRESSION_SPEED, "Rewind Compression Speed", "倒带压缩速度"),
    LANG_E(LANG_REWIND_INTERVAL, "Rewind Interval", "倒带间隔"),
    LANG_E(LANG_SCREEN_EFFECT, "Screen Effect", "屏幕效果"),
    LANG_E(LANG_SCREEN_SCALING, "Screen Scaling", "屏幕缩放"),
    LANG_E(LANG_SCREEN_SHARPNESS, "Screen Sharpness", "屏幕锐度"),
    LANG_E(LANG_SHADER_1, "Shader 1", "着色器 1"),
    LANG_E(LANG_SHADER_1_FILTER, "Shader 1 Filter", "着色器 1 滤镜"),
    LANG_E(LANG_SHADER_1_PROGRAM_TO_RUN, "Shader 1 program to run", "着色器 1 运行程序"),
    LANG_E(LANG_SHADER_1_SCALE, "Shader 1 Scale", "着色器 1 缩放"),
    LANG_E(LANG_SHADER_1_SOURCE_TYPE, "Shader 1 Source type", "着色器 1 源类型"),
    LANG_E(LANG_SHADER_1_TEXTURE_TYPE, "Shader 1 Texture Type", "着色器 1 纹理类型"),
    LANG_E(LANG_SHADER_2, "Shader 2", "着色器 2"),
    LANG_E(LANG_SHADER_2_FILTER, "Shader 2 Filter", "着色器 2 滤镜"),
    LANG_E(LANG_SHADER_2_PROGRAM_TO_RUN, "Shader 2 program to run", "着色器 2 运行程序"),
    LANG_E(LANG_SHADER_2_SCALE, "Shader 2 Scale", "着色器 2 缩放"),
    LANG_E(LANG_SHADER_2_SOURCE_TYPE, "Shader 2 Source type", "着色器 2 源类型"),
    LANG_E(LANG_SHADER_2_TEXTURE_TYPE, "Shader 2 Texture Type", "着色器 2 纹理类型"),
    LANG_E(LANG_SHADER_3, "Shader 3", "着色器 3"),
    LANG_E(LANG_SHADER_3_FILTER, "Shader 3 Filter", "着色器 3 滤镜"),
    LANG_E(LANG_SHADER_3_PROGRAM_TO_RUN, "Shader 3 program to run", "着色器 3 运行程序"),
    LANG_E(LANG_SHADER_3_SCALE, "Shader 3 Scale", "着色器 3 缩放"),
    LANG_E(LANG_SHADER_3_SOURCE_TYPE, "Shader 3 Source type", "着色器 3 源类型"),
    LANG_E(LANG_SHADER_3_TEXTURE_TYPE, "Shader 3 Texture Type", "着色器 3 纹理类型"),
    LANG_E(LANG_SHADER_EMULATOR_SETTINGS_PRESET, "Shader / Emulator Settings Preset", "着色器/模拟器设置预设"),
    LANG_E(LANG_THIS_WILL_CHOOSE_RESOLUTION_SOURCE_TO_SCALE_FROM, "This will choose resolution source to scale from", "选择缩放参考分辨率来源"),
    LANG_E(LANG_CHARGE_LED, "Charge LED", "充电 LED"),
    LANG_E(LANG_CHARGE_LED_DESC, "Show LED effects while charging", "充电时显示 LED 灯效"),
};

static LangId current_lang = LANG_ID_EN;

const char* LANG_get(LangKey key)
{
    if (key < 0 || key >= LANG_COUNT)
        return "";
    return current_lang == LANG_ID_ZH ? lang_entries[key].zh : lang_entries[key].en;
}

int LANG_set(LangId id)
{
    if (id < 0 || id >= LANG_ID_COUNT)
        return 0;
    current_lang = id;
    return 1;
}

LangId LANG_current(void)
{
    return current_lang;
}

const char* LANG_idName(LangId id)
{
    switch (id) {
        case LANG_ID_EN: return "English";
        case LANG_ID_ZH: return "简体中文";
        default: return "English";
    }
}
